# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b71ad67cfae1613af51363cb957e102a79cff08fb36ddaa307e7aa68c72e21275d682ae7f7ae0e4ece73f486c9d6a23ae8b5afa7672c23c97308f2044bd1839b

test:
  secret_key_base: ff2519836641040d471dd3cbcf155f51bf9005fa29cc17ddf18d0690139cc651a366486cb97da784e6ff0dbb827b3ea510ec9357b864460728a5166bc9e06d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
